version: "3"
services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    restart: unless-stopped
    ports:
      - 5432:5432
    # 获取默认配置
    # docker run -i --rm timescale/timescaledb:latest-pg15 cat /usr/local/share/postgresql/postgresql.conf.sample > postgresql.conf
    volumes:
      - ${PWD}/postgresql.conf:/etc/postgresql/postgresql.conf # 配置文件
      - ${HOME}/data/pgdata:/var/lib/postgresql/data # 数据存储位置挂载
    environment:
      POSTGRES_PASSWORD: 123456
    networks:
      - infrastructure

networks:
  infrastructure:
    external: true