version: "3"
services:
  mysql:
    image: mysql:8.0.32
    restart: unless-stopped
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ${PWD}/conf.d:/etc/mysql/conf.d # 配置文件
      - ${HOME}/data/mysql:/var/lib/mysql # 数据存储位置挂载
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # 强制,超级用户账号密码
      #MYSQL_DATABASE: things # 可选,启动时创建指定的数据库名称
      MYSQL_USER: things # 可选,授于指定MYSQL_DATABASE 超级权限
      MYSQL_PASSWORD: 123456 # 可选,授于指定MYSQL_DATABASE 超级权限
      TZ: Asia/Shanghai
      LANG: C.UTF-8
    networks:
      - infra

networks:
  infra:
    external: true
