version: "3"
services:
  redis:
    image: redis:6.2.5
    restart: unless-stopped
    volumes:
      - ${PWD}/conf:/usr/local/etc/redis
      - ${HOME}/data/redis:/data # 持久化数据挂载
    ports:
      - 6379:6379
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    mem_limit: 1GiB
    networks:
      - infra

networks:
  infra:
    external: true
