version: "3"
services:
  postgres:
    image: jaegertracing/all-in-one:1.42
    restart: unless-stopped
    ports:
      - 6831:6831/udp   # agent, jaeger.thrift over Thrift-compact
      - 6832:6832/udp   # agent, jaeger.thrift over Thrift-binary use by node.js
      - 5778:5778       # agent, serve configs
      - 16686:16686     # query, serve frontend
      - 4317:4317       # collector, OpenTelemetry  grpc
      - 4318:4318       # collector, OpenTelemetry http
      - 14250:14250     # collector, model.proto
      - 14268:14268     # collector, jaeger.thrift directly
      - 14269:14269     # collector, 
      - 9411:9411       # collector, Zipkin (option)
    # 获取默认配置
    # docker run -i --rm timescale/timescaledb:latest-pg15 cat /usr/local/share/postgresql/postgresql.conf.sample > postgresql.conf
    # volumes:
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
      COLLECTOR_OTLP_ENABLED: true
    networks:
      - infrastructure

networks:
  infrastructure:
    external: true